CREATE TABLE IF NOT EXISTS customer (
  id SERIAL PRIMARY KEY,
  billing_firstname TEXT,
  billing_lastname TEXT,
  billing_company TEXT,
  billing_address TEXT,
  billing_city TEXT,
  billing_state TEXT,
  billing_zip TEXT,
  billing_country TEXT,
  billing_phone TEXT,
  billing_mobile TEXT,
  billing_email TEXT,
  password TEXT,
  shipping_firstname TEXT,
  shipping_lastname TEXT,
  shipping_company TEXT,
  shipping_address TEXT,
  shipping_city TEXT,
  shipping_state TEXT,
  shipping_zip TEXT,
  shipping_country TEXT,
  shipping_phone TEXT,
  shipping_mobile TEXT,
  sendinvoice TEXT,
  conformance TEXT,
  terms TEXT,
  freight TEXT,
  note TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
